messaging/urls.py
from django.urls import path
from messaging.views import UserDetailView

from . import views

app_name = 'messaging'
urlpatterns = [
    # messages/
    path('', views.index, name='index'),
    # messages/1
    path('<int:question_id>/', views.detail, name='detail'),
    # messages/1/answer/
    path('<int:question_id>/answer', views.answer, name='answer'),
    path('question/', views.question, name='question'),
    path('search/', views.search, name='search'),
    path('profile/<int:pk>', UserDetailView.as_view(template_name="messaging/user_detail.html"), name='profile')
]

website/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('messages/', include('messaging.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

messaging/models.py
from django.db import models
from django.utils import timezone


class MessageManager(models.Manager):
    def create_message(self, content):
        message = self.create(content=content)
        return message


class Message(models.Model):
    content = models.CharField(max_length=2000)
    author = models.CharField(max_length=100, default="no_author")
    creation_date = models.DateTimeField(default=timezone.now)

    objects = MessageManager()

    def __str__(self):
        return self.content


class QuestionManager(models.Manager):
    def get_answered_questions(self):
        questions = self.exclude(answers=None)
        return questions


class Question(Message):
    title = models.CharField(max_length=200)

    objects = QuestionManager()

    def __str__(self):
        return self.title


class Answer(Message):
    parent = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')

messaging/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.detail import DetailView

from .models import Question
from django.contrib.auth.models import User


def index(request):
    questions_list = Question.objects.order_by('creation_date')[:5]
    context = {
        'questions_list': questions_list,
    }
    return render(request, 'messaging/index.html', context)


def detail(request, question_id):
    current_question = get_object_or_404(Question, pk=question_id)
    return render(request, 'messaging/detail.html', {'question': current_question})


def question(request):
    created_question = Question.objects.create(content=request.POST.get('question'),
                                               title=request.POST.get('title'),
                                               author=request.user)
    return redirect('messaging:detail', question_id=created_question.id)


@login_required
def answer(request, question_id):
    answered_question = get_object_or_404(Question, pk=question_id)
    answered_question.answers.create(content=request.POST.get('answer'),
                                     author=request.user)
    return redirect('messaging:detail', question_id=question_id)


def search(request):
    search_term = request.GET.get('search')
    questions_list = []
    if search_term:
        questions_list = Question.objects.get_answered_questions().filter(
            title__contains=search_term).order_by('creation_date')[:5]

    context = {
        'questions_list': questions_list,
    }
    return render(request, 'messaging/search.html', context)


class UserDetailView(DetailView):
    model = User

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

messaging/templates/messaging/__base.html
{% load staticfiles i18n %}
<!DOCTYPE html>

<html>
    <head>
        {% block meta_tags %}
        {% endblock meta_tags %}
        <title>{% block title %}{% trans "Django Messaging" %}{% endblock title %}</title>

        {% block stylesheets %}
        <link rel="stylesheet" href="{% static 'messaging/css/bootstrap.css' %}" type="text/css" />
        <link rel="stylesheet" href="{% static 'messaging/css/font-awesome.css' %}" type="text/css" />
        <link rel="stylesheet" href="{% static 'messaging/css/style.css' %}" type="text/css" />
        {% endblock stylesheets %}
        {% block javascript %}
        <script src="{% static 'messaging/js/jquery-3.3.1.js' %}" type="text/javascript"></script>
        <script src="{% static 'messaging/js/bootstrap.bundle.js' %}" type="text/javascript"></script>
        {% endblock javascript %}
        {% block extra_head %}
        {% endblock extra_head %}
    </head>
    <body>
        <header class="navbar navbar-fixed-top">
            {% include "messaging/_navigation.html" %}
        </header>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

messaging/templates/messaging/__l_single_col.html
{% extends "messaging/__base.html" %}

{% block content %}
    <main class="">
        {% block main_col %}{% endblock %}
    </main>
{% endblock %}

messaging/templates/messaging/_answer_create.html
<article>
    <h2>Répondre</h2>
    <form action="{% url 'messaging:answer' question.id %}" method="post">
    {% csrf_token %}
        <div class="form-group">
            <textarea type="text" name="answer" id="answer" value="" placeholder="Votre réponse"
                  rows="3" cols="40"></textarea>
        </div>

        <button type="submit" class="btn btn-info">Soumettre réponse</button>
    </form>
</article>

messaging/templates/messaging/_answer_details.html
{{ answer.content }}
<span class="text-right">
    {% include "messaging/_message_metadata.html" %}
</span>

messaging/templates/messaging/_answers_show.html
<article>
    <h2>Réponses</h2>
    <div>
    {% if question.answers.all %}
        {{ question.answers.all|length }} réponse(s).
    {% else %}
        Aucune réponse.
    {% endif %}
    </div>
    <ol>
        {% for answer in question.answers.all%}
            <li>{% include "messaging/_answer_details.html" with answer=answer %}</li>
        {% endfor %}
    </ol>
</article>

messaging/templates/messaging/_message_metadata.html
<span class="text-muted">{{ question.author }} : {{ question.creation_date|date:"d-m-Y H:i" }} </span>

messaging/templates/messaging/_navigation.html
<div>
    <a href="{% url 'messaging:index' %}" class="btn btn-info btn-lg">
        <span class="fa fa-home"></span> Django Messaging
    </a>
    <a href="{% url 'messaging:search' %}" class="btn btn-info btn-lg">
        <span class="fa fa-search"></span> Recherche
    </a>

    {% if request.user.is_authenticated %}
        <a href="{% url 'logout' %}?next={% firstof request.path '/' %}" class="btn btn-info btn-lg">
            <span class="fa fa-sign-out "></span> Logout
        </a>
        <a href="{% url 'messaging:profile' pk=request.user.id %}" class="btn btn-secondary btn-lg">
            <span class="fa fa-user"></span> {{ request.user }}
        </a>
    {% else %}
        <a href="{% url 'login' %}?next={% firstof request.path '/' %}" class="btn btn-info btn-lg">
            <span class="fa fa-sign-in fa-rotate-180"></span> Login
        </a>
    {% endif %}
</div>

messaging/templates/messaging/_question_details.html
<article>
    <h2 class="bg-info text-white">  {{ question.title }} </h2>
    <div>{{ question.content }}</div>
    <div class="text-right">
        {% include "messaging/_message_metadata.html" %}
    </div>
</article>

messaging/templates/messaging/_questions_search.html
<article>
    <h2>Rechercher :</h2>
    <div>Recherche parmis les questions ayant au moins une réponse :</div>
    <form action="{% url 'messaging:search' %}" method="get">
    <!--{% csrf_token %}-->
        <div class="form-group">
            <input type="text" name="search" id="search" value="" placeholder="Titre"/>
        </div>

        <button type="submit" class="btn btn-info">Rechercher</button>
    </form>
</article>

messaging/templates/messaging/_questions_show.html
<article>
    <h2>Questions :</h2>
    {% if questions_list %}
        <ol>
        {% for question in questions_list %}
            <li>{% include "messaging/_question_summary.html" %}</li>
        {% endfor %}
        </ol>
    {% else %}
        <p>Aucune question.</p>
    {% endif %}
</article>

messaging/templates/messaging/detail.html
{% extends "messaging/__l_single_col.html" %}


{% block main_col %}

{% include "messaging/_question_details.html" with question=question %}
{% if request.user.is_authenticated %}
    {% include "messaging/_answer_create.html" %}
{% else %}
<article>
    <h2>Répondre</h2>
    <a href="{% url 'login' %}?next={% firstof request.path '/' %}" class="text-info">Loguez vous pour répondre.</a>
</article>
{% endif %}
{% include "messaging/_answers_show.html" %}

{% endblock main_col %}

messaging/templates/messaging/index.html
{% extends "messaging/__l_single_col.html" %}


{% block main_col %}

{% include "messaging/_questions_show.html" %}
{% include "messaging/_question_create.html" %}

{% endblock %}

messaging/templates/messaging/search.html
{% extends "messaging/__l_single_col.html" %}


{% block main_col %}

{% include "messaging/_questions_search.html" %}
{% include "messaging/_questions_show.html" %}

{% endblock %}

messaging/templates/messaging/user_detail.html
{% extends "messaging/__l_single_col.html" %}


{% block main_col %}

<article>
    <div >
        <table>
            <tr>
                <td>Pseudo : <span class="text-info">{{ user.username }}</span></td>
            </tr>
            <tr>
                <td>Prénom : <span class="text-info">{{ user.first_name }}</span></td>
            </tr>
            <tr>
                <td>Nom : <span class="text-info">{{ user.last_name }}</span></td>
            </tr>
            <tr>
                <td>Mail : <span class="text-info">{{ user.email }}</span></td>
            </tr>
        </table>
    </div>
</article>

{% endblock %}